# Generated by Django 4.2.11 on 2024-04-19 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dars_xonalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xona_raqami', models.IntegerField()),
                ('qavat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh', models.IntegerField()),
                ('vaqt_start', models.TimeField()),
                ('vaqt_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='kunlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Kurslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_nomi', models.CharField(max_length=100)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=6)),
                ('davomiyligi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uqituvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('yunalishi', models.CharField(max_length=100)),
                ('tel_raqam', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Uquvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('t_sana', models.DateField()),
                ('tel_raqam', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tulovlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tulov', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vaqt', models.DateTimeField()),
                ('kurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.kurslar')),
                ('uquvchi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.uquvchilar')),
            ],
        ),
        migrations.CreateModel(
            name='guruh_kunlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.guruh')),
                ('kun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.kunlar')),
            ],
        ),
        migrations.AddField(
            model_name='guruh',
            name='kurs_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.kurslar'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='uqituvchi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.uqituvchilar'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='uquvchi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.uquvchilar'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='xona_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.dars_xonalari'),
        ),
    ]
